### ISSUE TITLE
Course target doesn't check first level 'or'

### ISSUE THREAD

**Issue by chaunmt** [chaunmt/Interactive-Prerequisite-Flowchart#126]
MATH 2263 should have STAT 5101 in its target because it's in the 1st level (info string), but it doesn't. It seems to be because it is nested in an 'or' dictionary.

**Comment by jahndan** [comment]
> code review moment 

 _Originally posted by @jahndan in [cb3e7b8](https://github.com/chaunmt/Interactive-Prerequisite-Flowchart/commit/cb3e7b8d918b2992205c9026080b80a2bf193e43#r149106587)_
