### ISSUE TITLE
Rename our website

### ISSUE THREAD

**Issue by chaunmt** [chaunmt/Interactive-Prerequisite-Flowchart#37]
There are many complaints that our current name "Gophers Prerequisite" isn't catchy enough. 
What other name can we go with?

**Comment by chaunmt** [comment]
Charequisite sounds cool lol

**Comment by Sin-ner0** [comment]
are we rebranding away from Goldy(the mascot)? Should we keep the theme(colors)

**Comment by chaunmt** [comment]
The project is now named "Course Flowchart."
