### ISSUE TITLE
Page routing and metadata

### ISSUE THREAD

**Issue by jahndan** [chaunmt/Interactive-Prerequisite-Flowchart#44]
Right now the dynamic routes accept any possible url
- [ ] dynamic routes only accept valid subjects and ids
- [x] bare minimum metadata (title)
- [x] a 404 page should load when an invalid url is used
- [ ] proper metadata generation

**Comment by chaunmt** [comment]
A simple 404 page is up. However, some components call for Access and pass by an invalid subject or id before calling the page --> Provoke an error message before provoke the 404 page. If anyone know their files are doing this, please fix it.
