### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by chaunmt** [chaunmt/Interactive-Prerequisite-Flowchart#47]
Our new README file is up. In DOCUMENTATION section, consider adding in a short introduction/guide for your work (either under the already listed item or make a new number for your work).
- [x] Contribution info
- [x] Mermaid
- [x] Reaflow/Reagraph
- [x] Coursedog API
- [x] graph generation stuff
- [x] Generate and access JSON files for data

**Comment by jahndan** [comment]
Is this ready to be closed?

**Comment by chaunmt** [comment]
> Is this ready to be closed?

In the documentation part, we agree that everyone will document their work in. Currently, I'm the only one did it.

**Comment by doggu** [comment]
close as not planned tbh
