### ISSUE TITLE
Display Team

### ISSUE THREAD

**Issue by chaunmt** [chaunmt/Interactive-Prerequisite-Flowchart#5]
- [ ] Set up configuration pages (i.e. web resolution page).
- [x] Set up global color file.
- [x] Create table of items in back-up plan page.
- [x] List necessary components that functionality team need to provide.
- [x] Organize the function components on home page.
- [x] Home page's css.
- [x] Set up global page layout (header, footer, sides).
- [ ] 2D flow chart page's css.
- [ ] Redesign home page.

**Comment by nonononono1** [comment]
Good news, I made home.js and I will research more on how to implement a website using such!

**Comment by nonononono1** [comment]
home page css halfway done??
