### ISSUE TITLE
Search filter options by subject, etc.

### ISSUE THREAD

**Issue by doggu** [chaunmt/Interactive-Prerequisite-Flowchart#87]
ok i was clicking stuff and made thjis issue but i am a bit confused on what this means, but it's likely just a matter of supplying the correct input data to the search bar in the first place (e.g. the editor search bar only gets all courses, while the global search bar gets both subjects and courses)

**Comment by chaunmt** [comment]
It should be a combination of both back-end and front-end. On back-end, it's just a simple function to get courses by a certain filter criteria. On the front-end, there should be option for user to choose their filter.
