### ISSUE TITLE
swap main and development

### ISSUE THREAD

**Issue by jahndan** [chaunmt/Interactive-Prerequisite-Flowchart#88]
make the `main` branch the one with active development, just have a branch called `release` for deployment

- we'll actually be able to use the github search feature with our current actively developed code (it only lets you search in the main branch)
- this project structure will be less confusing for people trying to onboard (when they clone, they'll actually see our latest code with things we're working on instead of a months-old version)

**Comment by chaunmt** [comment]
So is it that:
- `main` will be what `development` is right now.
- A branch name `release` will be made for deployment.
- What will happen to `development`? Should we delete it?

**Comment by jahndan** [comment]
basically, rename `main` to `release`
then, rename `development` to main
then, make `main` (formerly `development`) the main/protected branch
