### ISSUE TITLE
exports/imports clean up

### ISSUE THREAD

**Issue by jahndan** [chaunmt/Interactive-Prerequisite-Flowchart#89]
there's no real good reason to have default exports in library files, even if one export is most likely to be used.

obviously page and component files need to have their one default export, but generally they won't export anything else useful

but in library files, the difference between `import buildGraph from "..."` vs `import { buildGraph } from "..."` is not worth having the inconsistency between the default and other exports

- access
- graphbuilder
- *add others as needed*

**Comment by chaunmt** [comment]
is this one done yet?
