### ISSUE TITLE
Re-structure data file for courses

### ISSUE THREAD

**Issue by chaunmt** [chaunmt/Interactive-Prerequisite-Flowchart#99]
- Do not separate them by subject.
- Do not use CourseShell anymore, use Course only.
- [x] general.json that include all non-honors courses, excluding honors coursesin prereq.
- [x] honors.json that include any courses that need honors courses:
  + honors courses.
  + courseswith honors classes as prereq.

**Comment by jahndan** [comment]
the idea is basically: if the user cares about honors, they can change some setting on the site and the site will start including honors -- so the backend will start searching honors.json first and if it doesn't find the course it's looking for, it'll default back to general.json
